using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Quartz;

namespace Enigmatry.Entry.Scheduler;

[Obsolete("Migrate to OpenTelemetryJobListener instead.")]
internal sealed class ApplicationInsightsJobListener : IJobListener
{
    private readonly TelemetryClient _telemetryClient;

    public ApplicationInsightsJobListener(TelemetryClient telemetryClient)
    {
        _telemetryClient = telemetryClient;
    }

    public Task JobToBeExecuted(IJobExecutionContext context, CancellationToken cancellationToken = default) => Task.CompletedTask;

    public Task JobExecutionVetoed(IJobExecutionContext context, CancellationToken cancellationToken = default) => Task.CompletedTask;

    public Task JobWasExecuted(IJobExecutionContext context, JobExecutionException? jobException, CancellationToken cancellationToken = default)
    {
        TrackJobExecution(context, jobException);
        return Task.CompletedTask;
    }

    private void TrackJobExecution(IJobExecutionContext context, JobExecutionException? jobException = null)
    {
        var jobName = context.JobDetail.Key.Name;

        // Telemetry operation id is now automatically generated by Application Insights, so we don't need to set it manually.
        using var operation = _telemetryClient.StartOperation<RequestTelemetry>(jobName);
        var requestTelemetry = operation.Telemetry;
        requestTelemetry.Timestamp = context.FireTimeUtc;
        requestTelemetry.Duration = context.JobRunTime;

        if (jobException != null)
        {
            requestTelemetry.ResponseCode = "500";
            requestTelemetry.Success = false;

            _telemetryClient.TrackException(jobException);
        }
    }

    public string Name => nameof(ApplicationInsightsJobListener);
}
