trigger: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: false

variables:
  artifactName: enigmatry-entry-building-blocks
  projectNamePrefix: Enigmatry.Entry
  
resources:
  repositories:
    - repository: templates
      type: git
      name: Enigmatry - Azure Pipelines Templates/enigmatry-azure-pipelines-templates

jobs:
- template: code-analysis.yml@templates
  parameters:
    projectName: 'Enigmatry - Entry Building Blocks'
    sonarProjectKey: 'AspNetCoreAngular_EnigmatryBlueprintBuildingBlocks'
    displayName: 'Code Analysis'
    dotNetVersion: '9.0.x'

- template: build-report-job.yml@templates
  parameters:
    artifactName: $(artifactName)
    displayName: 'Generate Reports'
    projectNameAngularApp: ''
    projectNamePrefix: $(projectNamePrefix)